CREATE DATABASE `ycyw_rentals`;
USE `ycyw_rentals`;

DROP TABLE `USER` IF EXISTS;
CREATE TABLE `USER` (
	`id` INT PRIMARY KEY AUTO_INCREMENT,
	`last_name` VARCHAR(40) NOT NULL,
	`first_name` VARCHAR(40) NOT NULL,
	`date_of_birth` TIMESTAMP NOT NULL,
	`address` VARCHAR(255) NOT NULL,
	`zipcode` VARCHAR(10) NOT NULL,
	`city` VARCHAR(30) NOT NULL,
	`email` VARCHAR(255) NOT NULL,
	`password` VARCHAR(255) NOT NULL,
	`created_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`modified_date` TIMESTAMP NULL
);

DROP TABLE `ACRISS_CODE` IF EXISTS;
CREATE TABLE `ACRISS_CODE` (
	`id` INT PRIMARY KEY AUTO_INCREMENT,
	`code` CHAR(1) NOT NULL,
	`description` VARCHAR(512) NOT NULL,
	`created_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`modified_date` TIMESTAMP NULL
);

DROP TABLE `CATEGORY` IF EXISTS;
CREATE TABLE `CATEGORY` (
	`id` INT PRIMARY KEY AUTO_INCREMENT,
	`name` VARCHAR(40) NOT NULL,
	`description` VARCHAR(512) NOT NULL, NULL,
	`price` DECIMAL(10,2) NOT NULL,
	`created_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`modified_date` TIMESTAMP NULL
);

DROP TABLE `VEHICLE` IF EXISTS;
CREATE TABLE `VEHICLE` (
	`id` INT PRIMARY KEY AUTO_INCREMENT,
	`name` VARCHAR(40) NOT NULL,
	`description` VARCHAR(512) NOT NULL,
	`doors` INTEGER NOT NULL,
	`persons` INTEGER NOT NULL,
	`created_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`modified_date` TIMESTAMP NULL
);

DROP TABLE `ENERGY` IF EXISTS;
CREATE TABLE `ENERGY` (
	`id` INT PRIMARY KEY AUTO_INCREMENT,
	`name` VARCHAR(40) NOT NULL,
	`created_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`modified_date` TIMESTAMP NULL
);

DROP TABLE `GEARBOX` IF EXISTS;
CREATE TABLE `GEARBOX` (
	`id` INT PRIMARY KEY AUTO_INCREMENT,
	`name` VARCHAR(40) NOT NULL,
	`created_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`modified_date` TIMESTAMP NULL
);

DROP TABLE `AGENCY` IF EXISTS;
CREATE TABLE `AGENCY` (
	`id` INT PRIMARY KEY AUTO_INCREMENT,
	`address` VARCHAR(255) NOT NULL,
	`zipcode` VARCHAR(10) NOT NULL,
	`city` VARCHAR(30) NOT NULL,
	`latitude` DECIMAL(10,8) NOT NULL,
	`longitude` DECIMAL(10,8) NOT NULL,
	`email` VARCHAR(255) NOT NULL,
	`phone` VARCHAR(20) NOT NULL,
	`created_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`modified_date` TIMESTAMP NULL
);

DROP TABLE `ORDER` IF EXISTS;
CREATE TABLE `ORDER` (
	`id` INT PRIMARY KEY AUTO_INCREMENT,
	`start_date` TIMESTAMP NOT NULL,
	`end_date` TIMESTAMP NOT NULL,
	`price` DECIMAL(10,2) NOT NULL,
	`status` INT NOT NULL,
	`created_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`modified_date` TIMESTAMP NULL
);

DROP TABLE `PAYMENT` IF EXISTS;
CREATE TABLE `PAYMENT` (
	`id` INT PRIMARY KEY AUTO_INCREMENT,
	`reference` VARCHAR(50) NOT NULL,
	`mode` VARCHAR(50) NOT NULL,
	`price` DECIMAL(10,2) NOT NULL,
	`vat` DECIMAL(4,2) NOT NULL,
	`created_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`modified_date` TIMESTAMP NULL
);

DROP TABLE `COUNTRY` IF EXISTS;
CREATE TABLE `COUNTRY` (
	`id` INT PRIMARY KEY AUTO_INCREMENT,
	`name` VARCHAR(40) NOT NULL,
	`created_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`modified_date` TIMESTAMP NULL
);

DROP TABLE `OPTION` IF EXISTS;
CREATE TABLE `OPTION` (
	`id` INT PRIMARY KEY AUTO_INCREMENT,
	`name` VARCHAR(40) NOT NULL,
	`description` VARCHAR(512) NOT NULL,
	`price` DECIMAL(10,2) NOT NULL,
	`created_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`modified_date` TIMESTAMP NULL
);

DROP TABLE `ORDER_OPTION` IF EXISTS;
CREATE TABLE `ORDER_OPTION` (
	`order_id` INT NOT NULL,
	`option_id` INT NOT NULL,
	PRIMARY KEY (order_id, option_id)
);

ALTER TABLE `USER` ADD FOREIGN KEY (`country_id`) REFERENCES `COUNTRY` (`id`);
ALTER TABLE `CATEGORY` ADD FOREIGN KEY (`code_id`) REFERENCES `ACRISS_CODE` (`id`);
ALTER TABLE `VEHICLE` ADD FOREIGN KEY (`category_id`) REFERENCES `CATEGORY` (`id`);
ALTER TABLE `VEHICLE` ADD FOREIGN KEY (`agency_id`) REFERENCES `AGENCY` (`id`);
ALTER TABLE `VEHICLE` ADD FOREIGN KEY (`gearbox_id`) REFERENCES `GEARBOX` (`id`);
ALTER TABLE `VEHICLE` ADD FOREIGN KEY (`energy_id`) REFERENCES `ENERGY` (`id`);
ALTER TABLE `AGENCY` ADD FOREIGN KEY (`country_id`) REFERENCES `COUNTRY` (`id`);
ALTER TABLE `ORDER` ADD FOREIGN KEY (`user_id`) REFERENCES `USER` (`id`);
ALTER TABLE `ORDER` ADD FOREIGN KEY (`category_id`) REFERENCES `CATEGORY` (`id`);
ALTER TABLE `ORDER` ADD FOREIGN KEY (`start_agency_id`) REFERENCES `AGENCY` (`id`);
ALTER TABLE `ORDER` ADD FOREIGN KEY (`end_agency_id`) REFERENCES `AGENCY` (`id`);
ALTER TABLE `PAYMENT` ADD FOREIGN KEY (`order_id`) REFERENCES `ORDER` (`id`);
ALTER TABLE `ORDER_OPTION` ADD FOREIGN KEY (`order_id`) REFERENCES `ORDER` (`id`);
ALTER TABLE `ORDER_OPTION` ADD FOREIGN KEY (`option_id`) REFERENCES `OPTION` (`id`);

